# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zedlocales}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Zedkit"]
  s.date = %q{2010-12-10}
  s.default_executable = %q{zedlocales}
  s.description = %q{gem for localization support in Zedkit applications to generate locale files and load translations via the Zedkit API}
  s.email = %q{support@zedkit.com}
  s.executables = ["zedlocales"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/cli/config.rb",
    "lib/cli/projects.rb",
    "lib/cli/runner.rb",
    "lib/tasks/generate.rake",
    "lib/zedlocales.rb",
    "lib/zedlocales/content.rb",
    "lib/zedlocales/content_scopes.rb",
    "lib/zedlocales/content_sections.rb",
    "lib/zedlocales/projects.rb",
    "lib/zedlocales/railtie.rb",
    "lib/zedlocales/simple.rb",
    "lib/zedlocales/translations.rb",
    "test/helper.rb",
    "test/test_content.rb",
    "test/test_content_scopes.rb",
    "test/test_content_sections.rb",
    "test/test_locales.rb",
    "test/test_projects.rb",
    "test/test_simple_backend.rb",
    "test/test_translations.rb"
  ]
  s.homepage = %q{http://github.com/zedkit/zedlocales}
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{zedlocales}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{gem for localization support in Zedkit applications}
  s.test_files = [
    "test/helper.rb",
    "test/test_content.rb",
    "test/test_content_scopes.rb",
    "test/test_content_sections.rb",
    "test/test_locales.rb",
    "test/test_projects.rb",
    "test/test_simple_backend.rb",
    "test/test_translations.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<zedkit>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<human_hash>, [">= 0"])
    else
      s.add_dependency(%q<zedkit>, [">= 1.1.0"])
      s.add_dependency(%q<json>, [">= 1.4.4"])
      s.add_dependency(%q<human_hash>, [">= 0"])
    end
  else
    s.add_dependency(%q<zedkit>, [">= 1.1.0"])
    s.add_dependency(%q<json>, [">= 1.4.4"])
    s.add_dependency(%q<human_hash>, [">= 0"])
  end
end

