##
# Copyright (c) Zedkit.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

module Zedlocales
  class Simple
    class << self
      def get(locale)
        reshh = Zedkit::Client.get("locales/#{locale}/content", nil)
        yield(reshh) if (not reshh.nil?) && block_given?
        reshh
      end

      def set(locale, content)
        set_locale_in_simple_backend(locale, content)
      end

      protected
      def set_locale_in_simple_backend(locale, content)
        pp = ["#{Rails.root}",'config','locales',"#{locale}.rb"].join('/')
        File.open(pp, 'w') do |fd|
          fd.write locale_head
          fd.write locale_code(locale)
          fd.write content.human_inspect
          fd.write locale_end(fd)
        end
      end

      private
      def locale_head
        tmps  = "# encoding: UTF-8\n"
        tmps << "##\n"
        tmps << "# DO NOT EDIT THIS FILE.\n"
        tmps << "# This locale file is auto-generated from the ZedAPI by the ZedLocales Ruby gem. Any manual updates to an rb\n"
        tmps << "# file will be lost when this file is regenerated, with this current file only versioned once, or discarded.\n"
        tmps << "#   http://zedkit.com\n"
        tmps << "##\n\n"
      end
      def locale_code(locale)
        "{\n  :'#{locale}' =>\n\n"
      end
      def locale_end
        "\n\n}\n\n"
      end
    end
  end
end
